import 'package:app_updater/models/app_source_type.dart';
import 'package:app_updater/services/apk_installer_service.dart';
import 'package:app_updater/services/device_apps_service.dart';
import 'package:app_updater/services/fdroid_service.dart';
import 'package:app_updater/services/github_service.dart';
import 'package:app_updater/services/release_resolver.dart';
import 'package:app_updater/state/app_library.dart';
import 'package:app_updater/state/library_entry.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:http/http.dart' as http;
import 'package:http/testing.dart';
import 'package:shared_preferences/shared_preferences.dart';

import '../support/fake_curated_apps.dart';

class _FakeApkInstallerService extends ApkInstallerService {
  final List<String> installedPaths = [];

  /// 1-based index of the installApk() call that should throw, if any —
  /// simpler than matching on the generated file name, which is derived
  /// from the app's autogenerated (timestamp) id and so isn't known ahead
  /// of time.
  final int? failOnCallNumber;
  int _installCalls = 0;

  _FakeApkInstallerService({this.failOnCallNumber});

  @override
  Future<String> downloadApk({
    required String url,
    required String fileName,
    void Function(int received, int? total)? onProgress,
  }) async {
    onProgress?.call(1, 1);
    return '/tmp/$fileName';
  }

  @override
  Future<String> sha256Of(String filePath) async => 'deadbeef';

  @override
  Future<void> installApk(String filePath) async {
    _installCalls++;
    if (failOnCallNumber != null && _installCalls == failOnCallNumber) {
      throw Exception('install failed (call #$_installCalls)');
    }
    installedPaths.add(filePath);
  }
}

class _FakeDeviceAppsService extends DeviceAppsService {
  final List<Set<String>> snapshots;
  int calls = 0;

  _FakeDeviceAppsService(this.snapshots);

  @override
  Future<Set<String>> installedPackageNames() async {
    final snapshot = snapshots[calls.clamp(0, snapshots.length - 1)];
    calls++;
    return snapshot;
  }
}

// Network calls always fail fast, since these tests only exercise apps
// added via direct .apk URLs (which resolve without any HTTP request).
ReleaseResolver _offlineResolver() {
  final client = MockClient((request) async => http.Response('', 503));
  return ReleaseResolver(
    github: GithubService(client: client),
    fdroid: FdroidService(client: client),
  );
}

void main() {
  TestWidgetsFlutterBinding.ensureInitialized();

  setUp(() {
    SharedPreferences.setMockInitialValues({});
  });

  test(
    'downloadAndInstall downloads, hashes, installs and marks the app '
    'installed',
    () async {
      final installer = _FakeApkInstallerService();
      final library = AppLibrary(
        resolver: _offlineResolver(),
        installer: installer,
        deviceApps: _FakeDeviceAppsService([<String>{}]),
      );
      await library.load(curatedAppsOverride: testCuratedApps);
      // A package name is set up front so the fire-and-forget
      // detectPackageNameAfterInstall() call inside downloadAndInstall()
      // returns immediately instead of polling the fake in the background
      // for the rest of the test run.
      final app = await library.addCustomApp(
        name: 'MijnApp',
        type: AppSourceType.direct,
        source: 'https://example.com/mijnapp.apk',
        packageName: 'com.example.mijnapp',
      );

      await library.downloadAndInstall(app.id);

      final entry = library.entries.single;
      expect(entry.status, AppCheckStatus.upToDate);
      expect(entry.app.installedVersion, isNotNull);
      expect(entry.lastDownloadSha256, 'deadbeef');
      expect(installer.installedPaths, hasLength(1));
    },
  );

  test('downloadAndInstall does nothing without a resolved release', () async {
    final installer = _FakeApkInstallerService();
    final library = AppLibrary(
      resolver: _offlineResolver(),
      installer: installer,
    );
    await library.load(curatedAppsOverride: testCuratedApps);
    final app = await library.addCustomApp(
      name: 'BrokenApp',
      type: AppSourceType.github,
      source: 'owner/repo',
    );

    await library.downloadAndInstall(app.id);

    expect(installer.installedPaths, isEmpty);
  });

  test(
    'downloadAndInstallAll installs every updatable app, one at a time',
    () async {
      final installer = _FakeApkInstallerService();
      final library = AppLibrary(
        resolver: _offlineResolver(),
        installer: installer,
        deviceApps: _FakeDeviceAppsService([<String>{}]),
      );
      await library.load(curatedAppsOverride: testCuratedApps);
      await library.addCustomApp(
        name: 'AppOne',
        type: AppSourceType.direct,
        source: 'https://example.com/one.apk',
        packageName: 'com.example.one',
      );
      await library.addCustomApp(
        name: 'AppTwo',
        type: AppSourceType.direct,
        source: 'https://example.com/two.apk',
        packageName: 'com.example.two',
      );

      final result = await library.downloadAndInstallAll();

      expect(result.succeeded, 2);
      expect(result.failed, 0);
      expect(installer.installedPaths, hasLength(2));
      expect(
        library.entries.every((e) => e.status == AppCheckStatus.upToDate),
        isTrue,
      );
    },
  );

  test(
    'downloadAndInstallAll counts failures without stopping the batch',
    () async {
      final installer = _FakeApkInstallerService(failOnCallNumber: 1);
      final library = AppLibrary(
        resolver: _offlineResolver(),
        installer: installer,
        deviceApps: _FakeDeviceAppsService([<String>{}]),
      );
      await library.load(curatedAppsOverride: testCuratedApps);
      final bad = await library.addCustomApp(
        name: 'BadApp',
        type: AppSourceType.direct,
        source: 'https://example.com/bad.apk',
        packageName: 'com.example.bad',
      );
      final good = await library.addCustomApp(
        name: 'GoodApp',
        type: AppSourceType.direct,
        source: 'https://example.com/good.apk',
        packageName: 'com.example.good',
      );

      final result = await library.downloadAndInstallAll();

      expect(result.succeeded, 1);
      expect(result.failed, 1);
      final badEntry = library.entries.firstWhere((e) => e.app.id == bad.id);
      final goodEntry = library.entries.firstWhere((e) => e.app.id == good.id);
      expect(badEntry.status, isNot(AppCheckStatus.upToDate));
      expect(goodEntry.status, AppCheckStatus.upToDate);
    },
  );

  group('detectPackageNameAfterInstall', () {
    test('does nothing when the app already has a package name', () async {
      final deviceApps = _FakeDeviceAppsService([<String>{}]);
      final library = AppLibrary(
        resolver: _offlineResolver(),
        deviceApps: deviceApps,
      );
      await library.load(curatedAppsOverride: testCuratedApps);
      final app = await library.addCustomApp(
        name: 'MijnApp',
        type: AppSourceType.direct,
        source: 'https://example.com/mijnapp.apk',
        packageName: 'com.example.already-known',
      );

      await library.detectPackageNameAfterInstall(
        app.id,
        interval: Duration.zero,
      );

      expect(deviceApps.calls, 0);
      expect(
        library.entries.single.app.packageName,
        'com.example.already-known',
      );
    });

    test('records the package that appears after installing', () async {
      final deviceApps = _FakeDeviceAppsService([
        {'com.example.other'},
        {'com.example.other'},
        {'com.example.other', 'com.example.new'},
      ]);
      final library = AppLibrary(
        resolver: _offlineResolver(),
        deviceApps: deviceApps,
      );
      await library.load(curatedAppsOverride: testCuratedApps);
      final app = await library.addCustomApp(
        name: 'MijnApp',
        type: AppSourceType.direct,
        source: 'https://example.com/mijnapp.apk',
      );

      await library.detectPackageNameAfterInstall(
        app.id,
        attempts: 5,
        interval: Duration.zero,
      );

      expect(library.entries.single.app.packageName, 'com.example.new');
    });

    test('leaves the package name unset when nothing new appears', () async {
      final deviceApps = _FakeDeviceAppsService([{'com.example.other'}]);
      final library = AppLibrary(
        resolver: _offlineResolver(),
        deviceApps: deviceApps,
      );
      await library.load(curatedAppsOverride: testCuratedApps);
      final app = await library.addCustomApp(
        name: 'MijnApp',
        type: AppSourceType.direct,
        source: 'https://example.com/mijnapp.apk',
      );

      await library.detectPackageNameAfterInstall(
        app.id,
        attempts: 3,
        interval: Duration.zero,
      );

      expect(library.entries.single.app.packageName, isNull);
    });
  });
}
